name: ci-stable-release

on:
  push:
    branches: [main]
    paths:
      - "STABLE-RELEASE"
    #  - ".github/workflows/ci-stable-release.yml"

jobs:
  push-stable-version:
    name: Create KubeArmor stable release
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: v1.18

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Push the stable version of KubeArmor to Docker Hub
        env:
          REPO_OWNER: ${{ github.repository_owner }}
        run: STABLE_VERSION=$(cat STABLE-RELEASE) GITHUB_SHA=$GITHUB_SHA ./KubeArmor/build/push_kubearmor.sh stable

      - name: Install Cosign 
        uses: sigstore/cosign-installer@main

      - name: Get Image Digest
        id: digest
        run: | 
          ls -l
          echo "imagedigest=$(jq -r '.["containerimage.digest"]' kubearmor.json)" >> $GITHUB_OUTPUT
          echo "initdigest=$(jq -r '.["containerimage.digest"]' kubearmor-init.json)" >> $GITHUB_OUTPUT
          echo $imagedigest 
          echo $initdigest 

      - name: Sign the Container Images
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign -r ${{ github.repository_owner }}/kubearmor@${{ steps.digest.outputs.imagedigest }}
          cosign sign -r ${{ github.repository_owner }}/kubearmor-init@${{ steps.digest.outputs.initdigest }}
